<html>
    <head>
        <title>CFIT Inventory</title>
        <link rel="stylesheet" type="text/css" href="static/style.css">
        <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    </head>
    <body class="more textborder tacenter">
        <h1>More Functions</h1>
        <a class="button" href="./?act=low">Print Low Items</a>
        <a class="button" href="./?act=scanner">Associate Code</a>
        <a class="button" href="./?act=scanner&un&associate">Unassociate Code</a>
        <a class="button" href="./?act=ccategor">Back</a>
    </body>
<html>